# Generated by Django 4.1.7 on 2023-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamestore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
