# Generated by Django 4.1.7 on 2023-03-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamestore", "0002_alter_game_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_image",
            field=models.ImageField(upload_to="static/gamestore"),
        ),
    ]
