# Generated by Django 4.1.7 on 2023-03-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamestore", "0004_alter_game_game_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(max_length=150, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=40, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=40, verbose_name="Category title"),
        ),
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.CharField(max_length=150, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="game",
            name="slug",
            field=models.SlugField(max_length=40, verbose_name="Slug"),
        ),
    ]
