# Generated by Django 4.1.7 on 2023-03-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gamestore",
            "0005_alter_category_description_alter_category_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["name"], name="name_index"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["price"], name="price_index"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["category"], name="category_index"),
        ),
    ]
