# Generated by Django 4.1.7 on 2023-02-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Category title"),
                ),
                ("slug", models.SlugField(max_length=40, verbose_name="Category slug")),
                (
                    "description",
                    models.CharField(
                        max_length=150, verbose_name="Category description"
                    ),
                ),
                ("is_active", models.BooleanField(verbose_name="Category is active")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Game name")),
                (
                    "description",
                    models.CharField(max_length=150, verbose_name="Game description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Game is active"),
                ),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                ("release_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=4)),
                ("slug", models.SlugField(max_length=40, verbose_name="Game slug")),
                ("game_image", models.ImageField(upload_to="images/")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gamestore.category",
                        verbose_name="Category game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
            },
        ),
    ]
